### PR TITLE
chore: upgrade to sourcecred 0.11.2 (#88)

### LINKED ISSUE #88: Upgrade to SourceCred 0.11.2
https://app.dework.xyz/nation3/nationcred-p?taskId=90847fb0-067a-47d7-8e40-aa2b51d475ac

Switch to the official release at https://www.npmjs.com/package/sourcecred

More info:  https://github.com/sourcecred/sourcecred/releases

### PR DESCRIPTION
**Pull request by aahna-ashina**
https://app.dework.xyz/nation3/nationcred-p?taskId=90847fb0-067a-47d7-8e40-aa2b51d475ac

close #88

### CODE REVIEW

**Review by xPi2 — APPROVED** [review]

**Comment by aahna-ashina** [comment]
@johnmark13 I'm not able to start SourceCred locally because of a "JavaScript heap out of memory":

```javascript
nationcred-instance % yarn start
yarn run v1.22.19
$ dotenv -- sourcecred go --no-load && sourcecred serve
  GO   graph
  GO   reference detector for sourcecred/discord
 DONE  reference detector for sourcecred/discord: 0ms
  GO   reference detector for sourcecred/discourse
 DONE  reference detector for sourcecred/discourse: 24ms
  GO   reference detector for sourcecred/github
 DONE  reference detector for sourcecred/github: 12s
  GO   generating graph for sourcecred/discord
 DONE  generating graph for sourcecred/discord: 20s
  GO   generating graph for sourcecred/discourse
 DONE  generating graph for sourcecred/discourse: 382ms
  GO   generating graph for sourcecred/github
 DONE  generating graph for sourcecred/github: 20s
  GO   writing files
 DONE  writing files: 2206ms
 DONE  graph: 55s
  GO   contributions
  GO   writing files
 DONE  writing files: 141ms
 DONE  contributions: 746ms
  GO   hybrid
  GO   hybrid: running credrank
File not found at path: config/weights.json. Defaulting.
File not found at path: config/pluginBudgets.json. Defaulting.

<--- Last few GCs --->

[18576:0x7f8ebc100000]   279487 ms: Mark-sweep 4021.5 (4135.2) -> 4007.5 (4137.2) MB, 4966.6 / 0.0 ms  (average mu = 0.138, current mu = 0.022) allocation failure; scavenge might not succeed
[18576:0x7f8ebc100000]   285241 ms: Mark-sweep 4023.4 (4137.2) -> 4009.3 (4139.0) MB, 5703.7 / 0.0 ms  (average mu = 0.075, current mu = 0.009) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Are you having the same problem?

**Comment by aahna-ashina** [comment]
@johnmark13 Never, mind, found this:  https://github.com/nation3/nationcred-instance/blob/main/.github/workflows/generate-instance.yml#L15

```bash
export NODE_OPTIONS="--max-old-space-size=8192" 
```

**Comment by aahna-ashina** [comment]
@xPi2 Could you add @pythonpete32 to the Nation3 GitHub organization so that his PR review also gets counted?

> Screen Shot 2022-08-16 at 12 55 58 PM

**Comment by aahna-ashina** [comment]
# 🥹🙏

@johnmark13

**Comment by xPi2** [comment]
> @xPi2 Could you add @pythonpete32 to the Nation3 GitHub organization so that his PR approval also gets counted?
> 
> > Screen Shot 2022-08-16 at 12 57 07 PM

Invited

**Pull request merged**
