### PR TITLE
Updated Sourcecred version to 0.11.1 and regenerated yarn lock

### LINKED ISSUE #30: Upgrade to SourceCred 0.11.1
See https://github.com/sourcecred/template-instance/pull/126

### PR DESCRIPTION
**Pull request by johnmark13**
closes #30 By upgrading the Sourcecred library.

@aahna-ashina I realise now that I have also updated the grain.json to reintroduce the '"config": { "gnosis": true }' config element and that may not be what you want me to do, let me know and I will revert. Works locally, but unable to test with Nation3 files.

### CODE REVIEW

**Comment by aahna-ashina** [comment]
> closes #30 By upgrading the Sourcecred library.
> 
> @aahna-ashina I realise now that I have also updated the grain.json to reintroduce the '"config": { "gnosis": true }' config element and that may not be what you want me to do, let me know and I will revert. Works locally, but unable to test with Nation3 files.

Thanks, @johnmark13 🙌

You can test CSV generation by creating a new `grain-trigger-*` branch. I did it for you here (based on your PR branch): https://github.com/nation3/nationcred-instance/branches. This will trigger a grain distribution at https://github.com/nation3/nationcred-instance/actions/workflows/distribute-grain.yml

**Comment by aahna-ashina** [comment]
@johnmark13 Here is the output: https://github.com/nation3/nationcred-instance/tree/generated-ledger-1653020549/output/grainIntegration

**Review by aahna-ashina — COMMENTED** [review]
Looks good 👍

**Comment by johnmark13** [comment]
Gracias, nice to be involved!

**Pull request merged**
