### PR TITLE
chore: add github repo nation3/token-supply (#42)

### PR DESCRIPTION
**Pull request by aahna-ashina**
https://app.dework.xyz/nation3/meta-work?taskId=97537080-73c4-4231-8bb2-4028a30580c7

### CODE REVIEW

**Review by xPi2 — APPROVED** [review]

**Comment by aahna-ashina** [comment]
@tnrdd Could you review this PR, please?

**Comment by aahna-ashina** [comment]
# @johnmark13 🥹

**Review by xPi2 — APPROVED** [review]

**Comment by aahna-ashina** [comment]
# 🥹
@johnmark13 
# 🥹

**Review by johnmark13 — APPROVED** [review]
Keeping it alphabetical too 🙏

**Comment by aahna-ashina** [comment]
> Keeping it alphabetical too 🙏

OCD FTW 😄

**Pull request merged**
